config/routes.rb
Rails.application.routes.draw do

  root 'navigations#home' #:to => redirect('/admins/home')
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  resources :orders
  resources :meals

  match '/navigation_adminnavigation', to: 'navigations#adminnavigation', via: :get
  match '/current_menu', to: 'meals#current_menu', via: :get
  match '/order_history', to: 'orders#order_history', via: :get
  match '/navigation_studentnavigation', to: 'navigations#studentnavigation', via: :get
  match '/order_show', to: 'orders#show', via: :get
  match '/navigation_show_admin', to: "navigations#admin_show", via: :get
  match '/navigation_show_student', to: "navigations#student_show", via: :get
  match '/schedule', to: "meals#schedule", via: :post
  match '/tomorrows_menu', to: "meals#tomorrows_menu", via: :get

  match '/meal_show', to: 'meals#show', via: :get

  match "*path", to: "navigations#home", via: :all

end

app/controllers/navigations_controller.rb
class NavigationsController < ApplicationController
  before_filter :current_user
  def home
    if current_student
      redirect_to navigation_studentnavigation_path
    elsif current_admin
      redirect_to navigation_adminnavigation_path
    end
  end

  def adminnavigation
    unless current_admin
      flash[:warning] = 'You do not have permission to view that page.'
      redirect_to root_path
    end
  end

  def studentnavigation
    unless current_student
      flash[:warning] = 'You do not have permission to view that page.'
      redirect_to root_path
    end
  end

  def admin_show
    if current_admin
      @current_admin = Admin.find_by_admin_username(session[:admin_user])
    else
      redirect_to root_path
    end
  end

  def student_show
    if current_student
      @diet_hash = eval(current_student.dietary_restrictions)
      @current_student = Student.find_by_student_username(session[:student_user])
      @totalCal = 0
      Order.all.each do |order|
        if current_student.id == order.student_id
            meal = Meal.find(order.meal_id)
          @totalCal = @totalCal + meal.meal_calories.to_i
        end
      end
      @todays_calories = 0
      today = current_day
      Order.all.each do |order|
        if (today == order.created_at.strftime('%Y-%m-%d').to_date) and (current_student.id == order.student_id)
          meal = Meal.find(order.meal_id)
          @todays_calories = @todays_calories + meal.meal_calories.to_i
        end
      end
    else
      redirect_to root_path
    end
  end
end

app/views/navigations/admin_show.html.haml
%h1 #{current_admin.admin_first_name} #{current_admin.admin_last_name}'s Account

%h2 Email:
%h4 #{current_admin.email}

%h2 Username:
%h4 #{current_admin.admin_username}

%h2 Phone number:
%h4 #{current_admin.admin_phonenumber}


=button_to 'Edit Account', edit_admin_registration_path, method: :get, :class => 'general'
= button_to "Create New Admin Account", new_admin_registration_path, method: :get, :class => 'general'

app/views/navigations/adminnavigation.html.haml
%h1 Welcome #{@current_admin.admin_first_name} #{@current_admin.admin_last_name}!

%br
=button_to 'View Orders', orders_path, method: :get, :id => 'navigation_button'
%br
=button_to 'Schedule Menu', meals_path, method: :get, :id => 'navigation_button'
%br
=button_to 'See Account', navigation_show_admin_path(current_admin), method: :get, :id => 'navigation_button'

app/views/navigations/home.html.haml
%h1 Homepage

%h2 Student Login

=button_to 'Student Login', student_session_path, method: :get, :id => "login"
= link_to 'New student account', new_student_registration_path, method: :get
%br
%br
%h2 Admin Login

=button_to 'Admin Login', admin_session_path, method: :get, :id => "login"

app/views/navigations/student_show.html.haml
%h1 #{current_student.student_first_name} #{current_student.student_last_name}'s Account

%h2 Email:
%h4 #{current_student.email}

%h2 Username:
%h4 #{current_student.student_username}

%h2 Phone Number:
%h4 #{current_student.student_phonenumber}

%h2 Dietary Restrictions:
- if @diet_hash[:VGN] == false && @diet_hash[:VGT] == false && @diet_hash[:GF] == false && @diet_hash[:NF] == false && @diet_hash[:DF] == false
  %h4 None
- else
  - if @diet_hash[:VGN] == true
    %h4 Vegan
  - if @diet_hash[:VGT] == true
    %h4 Vegetarian
  - if @diet_hash[:DF] == true
    %h4 Dairy Free
  - if @diet_hash[:NF] == true
    %h4 Nut Free
  - if @diet_hash[:GF] == true
    %h4 Gluten Free
%h2 Total Calories:
%h4 #{@totalCal}

%h2 Today's Calories:
%h4 #{@todays_calories}
=button_to 'Edit Account', edit_student_registration_path, method: :get, :class => 'general'

app/views/navigations/studentnavigation.html.haml
%h1 Welcome #{@current_student.student_first_name} #{@current_student.student_last_name}!

=button_to 'Order', current_menu_path, method: :get, :id => 'navigation_button'
%br
  %br

=button_to 'Track Habits', order_history_path, method: :get, :id => 'navigation_button'