config/routes.rb
Rails.application.routes.draw do

  root 'navigations#home' #:to => redirect('/admins/home')
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  resources :orders
  resources :meals

  match '/navigation_adminnavigation', to: 'navigations#adminnavigation', via: :get
  match '/current_menu', to: 'meals#current_menu', via: :get
  match '/order_history', to: 'orders#order_history', via: :get
  match '/navigation_studentnavigation', to: 'navigations#studentnavigation', via: :get
  match '/order_show', to: 'orders#show', via: :get
  match '/navigation_show_admin', to: "navigations#admin_show", via: :get
  match '/navigation_show_student', to: "navigations#student_show", via: :get
  match '/schedule', to: "meals#schedule", via: :post
  match '/tomorrows_menu', to: "meals#tomorrows_menu", via: :get

  match '/meal_show', to: 'meals#show', via: :get

  match "*path", to: "navigations#home", via: :all

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  has_many :orders, dependent: :destroy
  validates_presence_of :meal_name
  validates_presence_of :meal_calories
  validates_presence_of :description
  def self.all_days
    %w[monday tuesday wednesday thursday friday saturday sunday]
  end

  def self.all_restrictions
    %w[VGN VGT GF NF DF]
  end

  def self.get_restriction_string(res)
    if res == :VGN
      'VGN'
    elsif res == :VGT
      'VGT'
    elsif res == :GF
      'GF'
    elsif res == :NF
      'NF'
    elsif res == :DF
      'DF'
    end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_filter :current_user
  def meal_params
    params.require(:meal).permit(:meal_name, :meal_calories, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :VGN, :VGT, :GF, :NF,:DF, :description)
  end

  def new
    # used by ADMIN to generate new meal options
    unless current_admin
      flash[:warning] = 'You do not have permission to view that page.'
      redirect_to root_path
    end
  end

  def create
    # used by ADMIN to generate new meal options
    diet_hash = Hash.new
    if meal_params[:VGN]
      diet_hash[:VGN] = true
    else
      diet_hash[:VGN] = false
    end
    if meal_params[:VGT]
      diet_hash[:VGT] = true
    else
      diet_hash[:VGT] = false
    end
    if meal_params[:GF]
      diet_hash[:GF] = true
    else
      diet_hash[:GF] = false
    end
    if meal_params[:NF]
      diet_hash[:NF]= true
    else
      diet_hash[:NF]= false
    end
    if meal_params[:DF]
      diet_hash[:DF] = true
    else
      diet_hash[:DF] = false
    end
    diet_hash = diet_hash.to_s
    @meal = Meal.new({:meal_name => meal_params[:meal_name], :meal_calories => meal_params[:meal_calories], :monday => meal_params[:monday], :tuesday=> meal_params[:tuesday], :wednesday=> meal_params[:wednesday], :thursday => meal_params[:thursday], :friday => meal_params[:friday], :saturday => meal_params[:saturday], :sunday => meal_params[:sunday], :dietary_restrictions => diet_hash, :description => meal_params[:description]})
    begin
    @meal.save!
    rescue Exception => e
      flash[:warning] = "Invalid meal. All fields must be filled out and the name must be unique."
      redirect_to new_meal_path

  else
    flash[:notice] = "#{@meal.meal_name} was successfully created."
    redirect_to meals_path
  end

  end

  def show
    # used by STUDENT to show the details of a specific meal options
    unless current_student
      flash[:warning] = 'You do not have permission to view that page.'
      redirect_to root_path
    end
    @meal = Meal.find(params[:id])
    respond_to do |format|
      format.html { render :partial => 'meal' and return if request.xhr? }
      format.xml { render :xml => @meal and return }
      format.json {render :json => @meal and return}
    end
  end

  def index
    # used by ADMIN to list all possible meal options
    unless current_admin
      flash[:warning] = 'You do not have permission to view that page.'
      redirect_to root_path
    end
    sort = params[:sort] || session[:sort]
    case sort
    when 'name'
      ordering, @name_header = {:meal_name => :asc}, 'hilite'
    when 'calories'
      ordering, @calorie_header = {:meal_calories => :asc}, 'hilite'
    when 'monday'
      ordering, @monday_header = {:monday => :desc}, 'hilite'
    when 'tuesday'
      ordering, @tuesday_header = {:tuesday => :desc}, 'hilite'
    when 'wednesday'
      ordering, @wednesday_header = {:wednesday => :desc}, 'hilite'
    when 'thursday'
      ordering, @thursday_header = {:thursday => :desc}, 'hilite'
    when 'friday'
      ordering, @friday_header = {:friday => :desc}, 'hilite'
    when 'saturday'
      ordering, @saturday_header = {:saturday => :desc}, 'hilite'
    when 'sunday'
      ordering, @sunday_header = {:sunday => :desc}, 'hilite'

    end

    @all_restrictions = Meal.all_restrictions
    @selected_admin_restrictions = params[:restrictions] || session[:restrictions] || {}

    selected_restrictions_array = []
    @meals = []

    @selected_admin_restrictions.each do |k, v|
      selected_restrictions_array << k
    end

    if selected_restrictions_array.empty?
      @meals = Meal.all.order(ordering)
    else
      Meal.all.order(ordering).each do |meal|
        temp_array = []
        eval(meal.dietary_restrictions).each do |k, v|
          if v == true
            temp_array << k.to_s
          end
        end

        if (selected_restrictions_array - temp_array).empty?
          @meals << meal
        end
      end
    end

    # @meals = Meal.all.order(ordering)
  end

  def edit
    # used by ADMIN to edit a specific meal option
    unless current_admin
      flash[:warning] = 'You do not have permission to view that page.'
      redirect_to root_path
    end
    @meal = Meal.find(params[:id])
    @restrictions = eval(@meal.dietary_restrictions)
  end

  def update
    # used by ADMIN to edit a specific meal option
    # not currently being used
  end

  def destroy
    # used by ADMIN to delete meal options
    @meal = Meal.find(params[:id])
    @meal.destroy
    flash[:notice] = "Meal '#{@meal.meal_name}' was deleted."
    redirect_to meals_path
  end

  def current_menu
    # used by STUDENT to give an index of meal options, filtered to show only today's menu and by dietary restrictions
    unless current_student
      flash[:warning] = 'You do not have permission to view that page.'
      redirect_to root_path
    end
    sort = params[:sort] || session[:sort]
    case sort
    when 'calories'
      ordering, @calories_header = {:meal_calories => :asc}, 'hilite'
    when 'meal_name'
      ordering, @meal_name_header = {:meal_name => :asc}, 'hilite'
    end

    today = Time.new.wday
    weekdays = { 0 => :sunday, 1 => :monday, 2 => :tuesday, 3 => :wednesday, 4 => :thursday, 5 => :friday, 6 => :saturday}

    @all_restrictions = Meal.all_restrictions
    @selected_restrictions = params[:restrictions] || session[:restrictions] || {}
    @student_restrictions = eval(current_student.dietary_restrictions)

    selected_restrictions_array = []
    @current_meals = []

    if params.has_key?(:account)
      @selected_restrictions.each do |k, v|
        selected_restrictions_array << k
      end
    else
      @student_restrictions.each do |k, v|
        if v
          selected_restrictions_array << Meal.get_restriction_string(k)
          @selected_restrictions[Meal.get_restriction_string(k)] = '1'
        end
      end
    end

    if selected_restrictions_array.empty?
      @current_meals = Meal.where(weekdays[today] => true).order(ordering)
    else
      Meal.where(weekdays[today] => true).order(ordering).each do |meal|
        temp_array = []
        eval(meal.dietary_restrictions).each do |k, v|
          if v == true
            temp_array << k.to_s
          end
        end

        if (selected_restrictions_array - temp_array).empty?
          @current_meals << meal
        end
      end
    end
  end

  def tomorrows_menu
    # used by STUDENT to see a preview of the next day's menu
    unless current_student
      flash[:warning] = 'You do not have permission to view that page. '
      redirect_to root_path
    end
    today = current_day.wday
    tomorrow = (today + 1) % 7 # since saturday is 6 and sunday is 0, this accounts for the switch
    weekdays = { 0 => :sunday, 1 => :monday, 2 => :tuesday, 3 => :wednesday, 4 => :thursday, 5 => :friday, 6 => :saturday}
    sort = params[:sort] || session[:sort]
    case sort
    when 'calories'
      ordering, @calories_header = {:meal_calories => :asc}, 'hilite'
    when 'name'
      ordering, @name_header = {:meal_name => :asc}, 'hilite'
    end
    @current_meals = Meal.where(weekdays[tomorrow] => true).order(ordering)
  end

  def schedule
    # admin uses to edit meals
    begin
    @meal = Meal.find_by_meal_name(params[:meal][:meal_name])
    diet_hash = Hash.new
    if meal_params[:VGN] == "1"
      diet_hash[:VGN] = true
    else
      diet_hash[:VGN] = false
    end
    if meal_params[:VGT] == "1"
      diet_hash[:VGT] = true
    else
      diet_hash[:VGT] = false
    end
    if meal_params[:GF] == "1"
      diet_hash[:GF] = true
    else
      diet_hash[:GF] = false
    end
    if meal_params[:NF] == "1"
      diet_hash[:NF]= true
    else
      diet_hash[:NF]= false
    end
    if meal_params[:DF] == "1"
      diet_hash[:DF] = true
    else
      diet_hash[:DF] = false
    end
    diet_hash = diet_hash.to_s
    @meal.update_attributes!({:meal_name => meal_params[:meal_name], :meal_calories => meal_params[:meal_calories], :monday => meal_params[:monday], :tuesday=> meal_params[:tuesday], :wednesday=> meal_params[:wednesday], :thursday => meal_params[:thursday], :friday => meal_params[:friday], :saturday => meal_params[:saturday], :sunday => meal_params[:sunday], :dietary_restrictions => diet_hash, :description => meal_params[:description]})
    flash[:notice] = "#{@meal.meal_name} was successfully updated."
    redirect_to meals_path
    rescue Exception => e
      flash[:warning] = 'An error occurred updating the meal, make sure all attributes are filled out'
      redirect_to meals_path
      end
  end
end

app/views/meals/_meal.html.haml
%p= @meal.description


= link_to 'Close', '', {:id => 'closeLink'}

app/views/meals/current_menu.html.haml
= javascript_include_tag 'application'
= javascript_include_tag 'diningplus'
%h1 Today's Menu
=button_to 'Cancel', navigation_studentnavigation_path, method: :get, :class => 'dangerButton'

= form_tag current_menu_path, :method => :get do
  = hidden_field_tag "calories_sort", true if @calories_header
  = hidden_field_tag "meal_name_sort", true if @meal_name_header
  %h3 Dietary Restrictions:
  = check_box_tag "restrictions[VGN]", 1, @selected_restrictions.include?("VGN"), :id => "restrictions_VGN", class: 'filter'
  = "Vegan"
  = check_box_tag "restrictions[VGT]", 1, @selected_restrictions.include?("VGT"), :id => "restrictions_VGT", class: 'filter'
  = "Vegetarian"
  = check_box_tag "restrictions[GF]", 1, @selected_restrictions.include?("GF"), :id => "restrictions_GF", class: 'filter'
  = "Gluten Free"
  = check_box_tag "restrictions[NF]", 1, @selected_restrictions.include?("NF"), :id => "restrictions_NF", class: 'filter'
  = "Nut Free"
  = check_box_tag "restrictions[DF]", 1, @selected_restrictions.include?("DF"), :id => "restrictions_DF", class: 'filter'
  = "Dairy Free"

  = hidden_field_tag "account", false

  = submit_tag 'Filter', :id => 'refresh_restrictions', :class => 'filterButton'


= form_tag orders_path do
  %table#orders
    %thead
      %tr
        %th{:class => @meal_name_header}= link_to 'Name', current_menu_path(:sort => 'meal_name', :restrictions => @selected_restrictions, :account => false), :id => 'meal_name_header'
        %th{:class => @calories_header}= link_to 'Calories', current_menu_path(:sort => 'calories', :restrictions => @selected_restrictions, :account => false), :id => 'calories_header'
        %th Details
        %th Select
    %tbody
      - @current_meals.each do |meal|
        %tr
          %td= meal.meal_name
          %td= meal.meal_calories
          %td= link_to "Details about #{meal.meal_name}", meal_path(meal), remote: true, method: :get, class: 'detailsLink'
          %td= radio_button_tag 'order[meal_id]', meal.id
  %br
  = submit_tag 'Order', :class => 'general', data: {disable_with: "Please wait..."}
=button_to "Preview #{weekday_to_string(Time.new.wday)}'s Menu", tomorrows_menu_path, method: :get, :class => 'general'

app/views/meals/edit.html.haml
%h1 Edit #{@meal.meal_name}

=button_to 'Cancel', meals_path, method: :get, :class => 'general'

=form_tag schedule_path, :id => 'edit' do
  = label :meal, :meal_name, 'Meal Name'
  = text_field :meal, 'meal_name'

  = label :meal, :meal_calories, 'Calories'
  = number_field :meal, 'meal_calories'
  %br/
  %h3 Schedule
  = hidden_field_tag 'meal[monday]', ''
  = check_box_tag 'meal[monday]', 1, @meal.monday
  = 'Monday'
  = hidden_field_tag 'meal[tuesday]', ''
  = check_box_tag 'meal[tuesday]', 1, @meal.tuesday
  = 'Tuesday'
  = hidden_field_tag 'meal[wednesday]', ''
  = check_box_tag 'meal[wednesday]', 1, @meal.wednesday
  = 'Wednesday'
  = hidden_field_tag 'meal[thursday]', ''
  = check_box_tag 'meal[thursday]', 1, @meal.thursday
  = 'Thursday'
  = hidden_field_tag 'meal[friday]', ''
  = check_box_tag 'meal[friday]', 1, @meal.friday
  = 'Friday'
  %br/
  = hidden_field_tag 'meal[saturday]', ''
  = check_box_tag 'meal[saturday]', 1, @meal.saturday
  = 'Saturday'
  = hidden_field_tag 'meal[sunday]', ''
  = check_box_tag 'meal[sunday]', 1, @meal.sunday
  = 'Sunday'
  %br/
  %h3 Dietary Restrictions
  = hidden_field_tag 'meal[VGN]', ''
  = check_box_tag 'meal[VGN]', 1, @restrictions[:VGN]
  = 'Vegan'
  = hidden_field_tag 'meal[VGT]', ''
  = check_box_tag 'meal[VGT]', 1, @restrictions[:VGT]
  = 'Vegetarian'
  = hidden_field_tag 'meal[GF]', ''
  = check_box_tag 'meal[GF]', 1, @restrictions[:GF]
  = 'Gluten Free'
  = hidden_field_tag 'meal[NF]', ''
  = check_box_tag 'meal[NF]', 1, @restrictions[:NF]
  = 'Nut Free'
  = hidden_field_tag 'meal[DF]', ''
  = check_box_tag 'meal[DF]', 1, @restrictions[:DF]
  = 'Dairy Free'
  %br/
  %br/
  = label :meal, :description, 'Description'
  = text_area :meal, 'description', value: @meal.description
  %br/
  %br/
  = submit_tag 'Update', :class => 'general', data: {disable_with: "Please wait..."}

app/views/meals/index.html.haml
%h1 Menu Schedule

%br
=link_to 'Add new meal', new_meal_path, method: :get
%br
%br
= form_tag meals_path, :method => :get do
  %h3 Dietary Restrictions:
  = check_box_tag "restrictions[VGN]", 1, @selected_admin_restrictions.include?("VGN"), :id => "restrictionsAdmin_VGN", class: 'filter'
  = "Vegan"
  = check_box_tag "restrictions[VGT]", 1, @selected_admin_restrictions.include?("VGT"), :id => "restrictionsAdmin_VGT", class: 'filter'
  = "Vegetarian"
  = check_box_tag "restrictions[GF]", 1, @selected_admin_restrictions.include?("GF"), :id => "restrictionsAdmin_GF", class: 'filter'
  = "Gluten Free"
  = check_box_tag "restrictions[NF]", 1, @selected_admin_restrictions.include?("NF"), :id => "restrictionsAdmin_NF", class: 'filter'
  = "Nut Free"
  = check_box_tag "restrictions[DF]", 1, @selected_admin_restrictions.include?("DF"), :id => "restrictionsAdmin_DF", class: 'filter'
  = "Dairy Free"
  = submit_tag 'Filter', :id => 'refresh_restrictions', :class => 'filterButton'

%br
%table#meals
  %thead
    %tr
      %th{:class => @name_header}= link_to 'Name', meals_path(:sort => 'name')
      %th{:class => @calorie_header}= link_to 'Calories', meals_path(:sort => 'calories')
      %th{:class => @monday_header}= link_to 'Mon', meals_path(:sort => 'monday')
      %th{:class => @tuesday_header}= link_to 'Tue', meals_path(:sort => 'tuesday')
      %th{:class => @wednesday_header}= link_to 'Wed', meals_path(:sort => 'wednesday')
      %th{:class => @thursday_header}= link_to 'Thu', meals_path(:sort => 'thursday')
      %th{:class => @friday_header}= link_to 'Fri', meals_path(:sort => 'friday')
      %th{:class => @saturday_header}= link_to 'Sat', meals_path(:sort => 'saturday')
      %th{:class => @sunday_header}= link_to 'Sun', meals_path(:sort => 'sunday')
  %tbody
    - @meals.each do |meal|
      %tr
        %td= meal.meal_name
        %td= meal.meal_calories
        %td= meal.monday ? "x" : ""
        %td= meal.tuesday ? "x" : ""
        %td= meal.wednesday ? "x" : ""
        %td= meal.thursday ? "x" : ""
        %td= meal.friday ? "x" : ""
        %td= meal.saturday ? "x" : ""
        %td= meal.sunday ? "x" : ""
        %td= button_to 'Edit', edit_meal_path(meal), :method => :get, :id => "#{meal.meal_name}editButton", :class => 'tableButton'
        %td= button_to 'Delete', meal_path(meal), :method => :delete, :id => "#{meal.meal_name}deleteButton", :class => 'tableButton', data: {disable_with: "Delete"}

app/views/meals/new.html.haml
%h1 Add New Meal

=button_to 'Cancel', meals_path, method: :get, :class => 'general'

= form_tag meals_path, :id => 'edit' do

  = label :meal, :meal_name, 'Meal Name'
  = text_field :meal, 'meal_name'

  = label :meal, :meal_calories, 'Calories'
  = number_field :meal, 'meal_calories'
  %br
  %br
  %h3 Schedule
  = check_box_tag 'meal[monday]', 1,false
  = 'Monday'
  = check_box_tag 'meal[tuesday]', 1,false
  = '  Tuesday'
  = check_box_tag 'meal[wednesday]', 1,false
  = '  Wednesday'
  = check_box_tag 'meal[thursday]', 1,false
  = '  Thursday'
  = check_box_tag 'meal[friday]', 1,false
  = '  Friday'
  %br/
  = check_box_tag 'meal[saturday]', 1,false
  = '  Saturday'
  = check_box_tag 'meal[sunday]', 1,false
  = '  Sunday'
  %br
  %br
  %h3 Dietary Restrictions
  = check_box_tag 'meal[VGN]', 1, false
  = 'Vegan'

  = check_box_tag 'meal[VGT]', 1, false
  = 'Vegetarian'

  = check_box_tag 'meal[GF]', 1, false
  = 'Gluten Free'

  = check_box_tag 'meal[NF]', 1, false
  = 'Nut Free'

  = check_box_tag 'meal[DF]', 1, false
  = 'Dairy Free'
  %br/
  %br/
  = label :meal, :description, 'Description'
  = text_area :meal, 'description'
  %br/
  %br/
  = submit_tag 'Add', :class => 'general', data: {disable_with: "Please wait..."}

app/views/meals/show.html.haml
%h1 Details about #{@meal.meal_name}
%h2 Calories: #{@meal.meal_calories}
- diet_hash = @meal.dietary_restrictions
- diet_hash = eval(diet_hash)
- diet_hash.delete_if{|key, value| value == false}
- if !diet_hash.empty?
    %h2 Dietary Restrictions:
    - if diet_hash[:VGN]
        Is vegan
        %br/
    - if diet_hash[:VGT]
        Is vegetarian
        %br/
    - if diet_hash[:GF]
        Is gluten free
        %br/
    - if diet_hash[:DF]
        Is dairy free
        %br/
    - if diet_hash[:NF]
        Is nut free
        %br/


%h2 Description:
#{@meal.description}
%br/
%br/
=link_to 'Back to Daily Menu', current_menu_path

app/views/meals/tomorrows_menu.html.haml
%h1 #{weekday_to_string(Time.new.wday)}'s Menu
=button_to 'Cancel', :back, method: :get, :class => 'dangerButton'

%table#orders
  %thead
    %tr
      %th{:class => @name_header}= link_to 'Name', tomorrows_menu_path(:sort => 'name')
      %th{:class => @calorie_header}= link_to 'Calories', tomorrows_menu_path(:sort => 'calories')
      %th Details
  %tbody
    - @current_meals.each do |meal|
      %tr
        %td= meal.meal_name
        %td= meal.meal_calories
        %td= link_to "Details about #{meal.meal_name}", meal_path(meal), class: "detailsLink"
  %br

=button_to "View Today's Menu", current_menu_path, method: :get, :class => 'general'