config/routes.rb
Rails.application.routes.draw do

  root 'navigations#home' #:to => redirect('/admins/home')
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  resources :orders
  resources :meals

  match '/navigation_adminnavigation', to: 'navigations#adminnavigation', via: :get
  match '/current_menu', to: 'meals#current_menu', via: :get
  match '/order_history', to: 'orders#order_history', via: :get
  match '/navigation_studentnavigation', to: 'navigations#studentnavigation', via: :get
  match '/order_show', to: 'orders#show', via: :get
  match '/navigation_show_admin', to: "navigations#admin_show", via: :get
  match '/navigation_show_student', to: "navigations#student_show", via: :get
  match '/schedule', to: "meals#schedule", via: :post
  match '/tomorrows_menu', to: "meals#tomorrows_menu", via: :get

  match '/meal_show', to: 'meals#show', via: :get

  match "*path", to: "navigations#home", via: :all

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Dining +
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %h1.title
      = link_to "Dining +", root_path, :id => 'title_link'
    - if current_admin
      =button_to "Main", navigation_adminnavigation_path, :method => :get, :id => "header_button"
      =button_to "Orders", orders_path, :method => :get, :id => "header_button"
      =button_to "Schedule", meals_path, :method => :get, :id => "header_button"
      =button_to "#{current_admin.admin_username}", navigation_show_admin_path(current_admin), :method => :get, :id => "header_button"
      =button_to "Logout", destroy_admin_session_path, :method => :delete, :id => "header_button"
    - if current_student
      =button_to "Main", navigation_studentnavigation_path, :method => :get, :id => "header_button"
      =button_to "Order", current_menu_path, :method => :get, :id => "header_button"
      =button_to "History", order_history_path, method: :get, :id => "header_button"
      =button_to "#{current_student.student_username}", navigation_show_student_path(current_student), :method => :get, :id => "header_button"
      =button_to "Logout", destroy_student_session_path, :method => :delete, :id => "header_button"


    #main
      %br
      - if flash[:notice]
        %br
        #notice.message= flash[:notice]

      - elsif flash[:warning]
        %br
        %br
        #warning.message= flash[:warning]

      = yield